### ISSUE TITLE
Issue with the Loop category blocks

### ISSUE THREAD

**Issue by xReaPerD** [mobile-blockly/flutter_blockly#7]
So the loop category inside the initialToolBoxJson would crash the workspace because of a syntax error.
here is the code 
```
<block type="controls_whileUntil">
     <field name="MODE">WHILE</field>
</block>',
```
So the ( ' ) and ( , ) causing the workspace to crash after you select the Loop category.
All we got to do it remove the ( ' ) and ( , ) .

**Comment by SerSerch** [comment]
@xReaPerD Hello!
thanks for the issue. this is fixed.
