### ISSUE TITLE
Blockly on the web takes over the entire page

### ISSUE THREAD

**Issue by sajjaduc** [mobile-blockly/flutter_blockly#8]
Blockly on the web takes over the entire page, and even Scaffold/AppBar isn't displayed. I have tried putting the editor in a container and sized box as well but the constraints aren't respected as well.

**Comment by sajjaduc** [comment]
Thanks @SerSerch. Please, let me know if I can help in any way.

**Comment by SerSerch** [comment]
@sajjaduc one of the problems with [flutter (web)](https://github.com/mobile-blockly/flutter_blockly/blob/main/example/web/index.html#L51) is that all elements have position absolute.
or all elements are rendered in canvas
```
  <script>
    window.addEventListener('load', function(ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        },
        onEntrypointLoaded: function(engineInitializer) {
          // config with html or canvas (default)
          engineInitializer.initializeEngine({
            renderer: "html",
          }).then(function(appRunner) {
            appRunner.runApp();
          });
        }
      });
    });
  </script>
```

flutter_blockly adds an editor [using JS](https://github.com/mobile-blockly/flutter_blockly/blob/main/lib/src/blockly_editor_web.dart#L246)

I added "style" so that [styles](https://github.com/mobile-blockly/flutter_blockly/blob/main/lib/src/html/html_style.dart) can be controlled
``` dart
BlocklyEditorWidget(
          workspaceConfiguration: workspaceConfiguration,
          initial: initialJson,
          onInject: onInject,
          onChange: onChange,
          onDispose: onDispose,
          onError: onError,
          style: '.wrapper-web {top:58px;bottom:50px}',
        ),
      )
```
It's all I can do (v1.4.4)
I hope this helps you

**Comment by sajjaduc** [comment]
Thanks @SerSerch. 

Would it be possible to put the editor in a `Container` and dynamically change `style` based on the constraints of the `Container` as that will pretty much achieve what we want?

**Comment by SerSerch** [comment]
@sajjaduc good idea, I'll try to add that

**Comment by SerSerch** [comment]
@sajjaduc flutter_blockly 1.4.5

**Comment by sajjaduc** [comment]
Thanks @SerSerch. It seems this still requires use of manually passing in `style` with the top and width etc to set it up correctly. Is my understanding correct?

**Comment by sajjaduc** [comment]
Wouldn't it be better to use `webview_flutter_web` package and using `loadHtmlString` to add the div for the editor, instead of just adding it directly to the root?

**Comment by SerSerch** [comment]
@sajjaduc yes, you still need to pass the style
```css
.wrapper-active {top:58px; left:0;}
```
but the height and width are determined automatically.

webview_flutter_web it is iframe
this is a bad implementation

I will look for some new solution to make it ok

**Comment by SerSerch** [comment]
@sajjaduc Hi. I finally found a solution [HtmlElementView](https://api.flutter.dev/flutter/widgets/HtmlElementView-class.html)
there will be an update soon

```dart
  @override
  void initState() {
      super.initState();
      platformViewRegistry.registerViewFactory(
        'blocklyEditor',
        (int viewId, {Object? params}) {
          final divElement = DivElement();
          divElement.id = 'blocklyEditor';
          return divElement;
        },
      );
  }
  
  @override
  Widget build(BuildContext context) {
    return const HtmlElementView(viewType: 'blocklyEditor');
  }
```
